name: Code Quality

on: [push, pull_request]

jobs:
  qualitycheck:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
            python -m pip install --upgrade pip
            pip install pandas numpy torch rdkit tqdm
            pip install pytest pytest-cov

    - name: Run tests
      run: pytest --cov=ChemSpaceAL
